services:
  postgres:
    image: postgres:17-alpine
    container_name: realtime-chat-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - '${POSTGRES_PORT}:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - realtime-chat-network

  mongo:
    image: mongo:8.0
    container_name: realtime-chat-mongo
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

    ports:
      - '${MONGO_PORT}:27017'

    volumes:
      - mongo_data:/data/db

    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mongosh --quiet --eval "db.adminCommand(''ping'').ok" --username ${MONGO_ROOT_USERNAME} --password ${MONGO_ROOT_PASSWORD} --authenticationDatabase admin',
        ]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - realtime-chat-network

  redis:
    image: redis:8-alpine
    container_name: realtime-chat-redis
    restart: unless-stopped

    command:
      [
        'redis-server',
        '--appendonly',
        'yes',
        '--requirepass',
        '${REDIS_PASSWORD}',
        '--notify-keyspace-events',
        'Ex',
      ]

    ports:
      - '${REDIS_PORT}:6379'

    volumes:
      - redis_data:/data

    healthcheck:
      test: ['CMD-SHELL', 'redis-cli -a ${REDIS_PASSWORD} ping | grep PONG']
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - realtime-chat-network

volumes:
  postgres_data:
  mongo_data:
  redis_data:

networks:
  realtime-chat-network:
    driver: bridge
